[build]
  base = "chain-crm"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  SAHIBA_API_TOKEN = "Sahiba_CZSfEghwaD4s"

[[redirects]]
  from = "/api/query"
  to = "/.netlify/functions/query"
  status = 200
